### ISSUE TITLE
Retrieve the whole file instead of chunks

### ISSUE THREAD

**Issue by staniel359** [kokarare1212/librespot-python#101]
Hello.
I've noticed that `stream.input_stream.stream().read()` command retrieves audio file by chunks, one by one, which takes time.
Is there a reason why it doesn't download the whole file?

**Comment by kokarare1212** [comment]
It has already been implemented.
You can now get all streams by entering a number less than or equal to 0 in the read argument.
Please refer to the following code.
https://github.com/kokarare1212/librespot-python/blob/447c4f41162752b97f5dbbd087248a8daefea5ca/librespot/audio/__init__.py#L150-L198

**Comment by staniel359** [comment]
@kokarare1212 I tried entering `0`, but seems like it is already a default value.

What I see is this:
![изображение](https://user-images.githubusercontent.com/18214933/147073665-000f2486-0f10-478b-878a-26f1e9074e65.png)
43 chunks are processed one by one.
Is it possible to process the whole file at once?

**Comment by kokarare1212** [comment]
I'm sure it's technically possible but I don't think this is realistic because it will be slow to retry when network or other errors occur.
The upstream librespot-java also uses the current method.

**Comment by staniel359** [comment]
@kokarare1212 I see, thanks.
