### ISSUE TITLE
[BUG] Memory Leak

### ISSUE THREAD

**Issue by owlwang** [kokarare1212/librespot-python#141]
Hi, thank you for making this very useful project, it's really awesome.

I'm experiencing a suspected memory leak during my use.

When downloading a large batch of songs, I can see the memory usage slowly growing.

I'd like to ask you if there are any areas I can look at to help locate a fix for this memory leak?

My environment is Ubuntu 20 and python 3.8.

sample code:
```python

import sys

from librespot.core import Session
from librespot.metadata import TrackId
from librespot.audio.decoders import AudioQuality, VorbisOnlyAudioQuality

account_user = ''
account_passwd = ''
session = Session.Builder().user_pass(account_user, account_passwd).create()


def download_from_spotify(track_id):
    spotify_track_id = TrackId.from_uri('spotify:track:' + track_id)
    stream = session.content_feeder().load(spotify_track_id, VorbisOnlyAudioQuality(AudioQuality.NORMAL), False, None)
    audio_buffer = stream.input_stream.stream().read()
    with open(f'{track_id}.ogg', 'wb') as f:
        f.write(audio_buffer)


def main():
    target = sys.argv[1]
    with open(target, 'r') as f:
        for line in f:
            track_id = line.strip()
            download_from_spotify(track_id)


if __name__ == '__main__':
    main()


```

**Comment by kokarare1212** [comment]
Side note:
> We DO NOT encourage piracy and DO NOT support any form of downloader/recorder designed with the help of this repository and in general anything that goes against the Spotify ToS.

**Comment by owlwang** [comment]
Okay.

**Comment by owlwang** [comment]
Hope you can notice this issue.
I've located the memory leak. 
Python's GC doesn't seem to recycle the used buffer, so every time a song is loaded it stays in memory permanently.

## Temporary solution
Add a method to clear the buffer in the InternalStream class

```python
  class InternalStream(AbsChunkedInputStream):
          streamer: CdnManager.Streamer
+        def clear_buffer(self):
+            del self.streamer.buffer
```

Call the clear_buffer() method in the close method of the AbsChunkedInputStream class

```python
 def close(self) -> None:
+    self.closed = True
     self.clear_buffer()
     with self.wait_lock:
         self.wait_lock.notify_all()
```

Then after each read(), call close() method.
```python
def load_data_from_spotify(track_id):
    spotify_track_id = TrackId.from_uri('spotify:track:' + track_id)
    stream = session.content_feeder().load(spotify_track_id, VorbisOnlyAudioQuality(AudioQuality.NORMAL), False, None)
    audio_buffer = stream.input_stream.stream().read()
    # dosomething
    audio_buffer.close() # must add this, to clear buffer
```

Hope you can fix this problem in main branch code.

**Comment by kokarare1212** [comment]
Yes, that is because the buffer has not been released.

**Comment by owlwang** [comment]
Thanks for your work!

**Comment by staniel359** [comment]
@kokarare1212 When will these changes be released?

**Comment by kokarare1212** [comment]
OK, I have published.
https://github.com/kokarare1212/librespot-python/releases/tag/v0.0.6

**Comment by staniel359** [comment]
@kokarare1212 Thank you.
