### ISSUE TITLE
[REQUEST] class PlaylistId(SpotifyId):

### ISSUE THREAD

**Issue by sesseor** [kokarare1212/librespot-python#173]
**Is your feature request related to a problem? Please describe.**
i saw that `AlbumId` /`ArtistId`/ `ShowId` classes are implemented but not a playlist class
 
**Describe the solution you'd like**
i tried to add it myself  and added all the needed functions but got stuck here `librespot/proto/Metadata_pb2.py` and did not know what to do 
also `get_metadata_4_playlist()` would be a cool thing to get

**Comment by kokarare1212** [comment]
It can be obtained at `ApiClient.get_player(_id: PlaylistId)`.
```
session = ~
playlist_id = PlaylistId.from_uri("spotify:playlist:*")
playlist = session.api().get_playlist(playlist_id)
```

**Comment by sesseor** [comment]
fantastic.. this works fine 
what does `session.api().get_playlist(playlist_id)` return ? like the type ?
and what are those ? `\000\000\000\007>\177\341\305\014\301\242\013\255\310u\337\253\224_\370/+_d`

**Comment by kokarare1212** [comment]
`session.api().get_playlist(playlist_id)` does return a protobuf data (SelectedListContent).
For more information, please see
https://github.com/kokarare1212/librespot-python/blob/main/proto/playlist4_external.proto#L168-L181
