### ISSUE TITLE
[BUG] PremiumAccountRequired error

### ISSUE THREAD

**Issue by rphlo** [kokarare1212/librespot-python#193]
**Describe the bug**
Login fails with Session.SpotifyAuthenticationException PremiumAccountRequired

**To Reproduce**
Try to log in with premium account

**Expected behavior**
Should login without exceptions

**Client Information (please complete the following information):**
 - OS: Debian
 - Python Version 3.11.2
 - Library Version 0.0.8

**Additional context**
It use to work, so I suspect changes on Spotify side

**Comment by kokarare1212** [comment]
I was able to confirm this as well.
The same error seems to occur with librespot-java.
I'm not sure, so I'll wait for changes to librespot-java...

**Comment by deermichel** [comment]
yup same here, however the rust version still works: https://github.com/librespot-org/librespot

**Comment by kokarare1212** [comment]
These problems should be fixed in [this release](https://github.com/kokarare1212/librespot-python/releases/tag/v0.0.9).
The reason seems to be that the client version is too old.
See also: https://github.com/librespot-org/librespot-java/issues/614#issuecomment-1550325165
