### ISSUE TITLE
[REQUEST] Create session using user's token

### ISSUE THREAD

**Issue by staniel359** [kokarare1212/librespot-python#195]
**Is your feature request related to a problem? Please describe.**

I'm running your library on a server for multiple users.
Right now I'm using my own Spotify credentials for all users.
When a user decides to connect their account, instead of storing their credentials I'd like to store their access token (for security reasons) and use it to create each user's session.

**Describe the solution you'd like**

`Session.Builder().token(<USER_TOKEN>)`

**Comment by kokarare1212** [comment]
Perhaps this should work.
```python
session = Session.Builder() \
    .user_pass("<email address>", "<password>") \
    .create()

stored_credentials = session.stored()
session2 = Session.Builder().stored(stored_credentials).create()
```

**Comment by staniel359** [comment]
@kokarare1212 But what if I don't want to use any users' emails or passwords?
Is it possible to login user via their token?

**Comment by kokarare1212** [comment]
It is necessary for the first login, but from the next time onward, such a thing can be done by obtaining something like a token in session.stored and passing it as an argument to Session.Builder.stored, as in the above code.

**Comment by staniel359** [comment]
@kokarare1212 Okay, thanks.

**Comment by prime-rue** [comment]
> It is necessary for the first login, but from the next time onward, such a thing can be done by obtaining something like a token in session.stored and passing it as an argument to Session.Builder.stored, as in the above code.

I can't get it to work. Could you please explain to me how I could use the following credentials to create a session?

{'access_token': 'BQAHHtai9r6xIHb2SPVYUCMG7XCoDbzhZGX0Qz-XXXXXXXXXXXXXXXXXX-uYj6g41R_PFQGMru5b60ZVkPiW83Dutw8VVRd35BAEJB0mRfBaeFU8aEhiDxF8Toy5gVI7eoaC_6Cn36So
-Ztx6me1SBMe_BMu6i_FBhUfJyTWTyjINX5whrTnwgqRcDlUu6ps8tl0iv_uwYA1FjRXjrnZmLXXXXXXXXXXXXXXXX',
 'token_type': 'Bearer',
 'expires_in': 3600,
 'refresh_token': 'AQBLAs-XXXXXXXXXXXXXXXXXX-BMfRqEqZaAtZLzaRAmGny1jnseoOSOD_tDDB5GbwERZDYvqTMz26HMmDA32Rpw3UmEz3lhXk7z3NUAMjsxkr_yNLgTb273HrDdrxc3NwI',
 'scope': 'user-library-read',
 'expires_at': 1748377911}

I tried: 

session = Session.Builder()

session.login_credentials = Authentication.LoginCredentials(
    typ=Authentication.AUTHENTICATION_SPOTIFY_TOKEN,
    username=SPOTIPY_CLIENT_USERNAME, # The username I specified for receiving the credentials.
    auth_data=b'access_token'
)

session = session.create()

**Comment by kokarare1212** [comment]
@prime-rue You probably cannot use Web API tokens.
