### ISSUE TITLE
[REQUEST] change stored_credentials path

### ISSUE THREAD

**Issue by van4oza** [kokarare1212/librespot-python#251]
I'm trying to use librespot in AWS Lambda, but the only RW dir there is /tmp. librespot keeps creating credentials file in os.getcwd(). even if I override it keeps getting back and failing

```
spotify_builder = Session.Builder()
spotify_builder.conf.stored_credentials_file = "/tmp/conf/spotify_credentials.json"
session = spotify_builder.user_pass("test@test.test", "mypswd").create()
```

Probably there is solution already?

**Comment by kokarare1212** [comment]
Perhaps passing Session.Configuration as an argument to the constructor of Session.Builder will work.

https://github.com/kokarare1212/librespot-python/blob/main/librespot/core.py#L1367-L1420
https://github.com/kokarare1212/librespot-python/blob/main/librespot/core.py#L1690-L1840

**Comment by van4oza** [comment]
thx!
