### ISSUE TITLE
How does it work, and is it legal?

### ISSUE THREAD

**Issue by oifj34f34f** [kokarare1212/librespot-python#255]
As far as I know, Spotify uses DRM, which supposedly can't be bypassed. I'm wondering how downloading a track works without a Premium account (with 160kbps ogg of course but still). Is https://github.com/librespot-org/librespot a "legal" Spotify client library with restrictions for free accounts so as not to violate Spotify's terms of service?"

**Comment by kokarare1212** [comment]
Yes and no about Spotify DRM.
Spotify uses AAC + Widevine in the web player but not in the native application (Vorbis). (Plain encryption is used instead).

Also, we will not determine if the librespot-related project is illegal or violates the ToS, at least not outside the scope of this project, so ask a legal expert, or ask Spotify AB. or look at [the librespot issue](https://github.com/librespot-org/librespot/issues?q=) Please see.

**Comment by oifj34f34f** [comment]
Ok, thanks for the reply
