### ISSUE TITLE
[BUG] RuntimeError: Failed fetching audio key!

### ISSUE THREAD

**Issue by lutskboy** [kokarare1212/librespot-python#264]
Script not work

RuntimeError: Failed fetching audio key! gid: 247615c5fbf84ed1997bbfd0532b4b3e, fileId: 9b27fb4a739a50d3a1d666bb5f72bcdef8753de0

**Comment by kokarare1212** [comment]
**Please submit your issue according to the issue template.**

Generally, either you are not allowed to listen to music in your country of residence, or you have chosen a high sound quality for a non-premium account.
