### ISSUE TITLE
You need to change one of the dependencies to "pycryptodomex" :)

### ISSUE THREAD

**Issue by Footsiefat** [kokarare1212/librespot-python#51]
It would normally give an error of 
"No module named 'Cryptodome'"
unless I ran 
"pip3 install pycryptodomex" to solve it

your welcome :)

**Comment by kokarare1212** [comment]
Thank you for your inquiry.
The relevant part has been corrected.
https://github.com/kokarare1212/librespot-python/commit/e78988a38fc3d8153f0358d9cac1147bbdeeb70b
