### ISSUE TITLE
Invalid PEP 440 version: 0.0.1-SNAPSHOT

### ISSUE THREAD

**Issue by nyuszika7h** [kokarare1212/librespot-python#54]
Your library cannot be installed with [Poetry](https://python-poetry.org/), it throws the following error:

```
InvalidVersion

Invalid PEP 440 version: '0.0.1-SNAPSHOT'

at ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/core/version/pep440/parser.py:67 in parse
     63│     @classmethod
     64│     def parse(cls, value: str, version_class: Optional[Type["PEP440Version"]] = None):
     65│         match = cls._regex.search(value) if value else None
     66│         if not match:
  →  67│             raise InvalidVersion(f"Invalid PEP 440 version: '{value}'")
     68│ 
     69│         if version_class is None:
     70│             from poetry.core.version.pep440.version import PEP440Version
     71│ 
```

Removing `-SNAPSHOT` should fix this issue.

**Comment by kokarare1212** [comment]
Thank you for your inquiry.

https://github.com/kokarare1212/librespot-python/commit/4909f16474045d82e3557e63d6a08c87f7a404a1 https://github.com/kokarare1212/librespot-python/commit/424eeb1125d84243ec50ec28c2400ba5ff311055

Removed `-SNAPSHOT` from the version.
Please check if it works again.

kokarare1212

**Comment by nyuszika7h** [comment]
Seems to work fine now.
