### ISSUE TITLE
Is it possible to save session?

### ISSUE THREAD

**Issue by staniel359** [kokarare1212/librespot-python#77]
Hello. I wrote a script for audio fetching using your library. But the problem is each time the script is executed, each time session is created and it takes time. Is it possible to initialize session once for multiple script runs?

**Comment by kokarare1212** [comment]
Thank you for your inquiry.
Session connects to Spotify's server via a socket, which slows down the initialization process.
I don't know what kind of multiple scripts you are referring to, but you might want to use [threading](https://docs.python.org/3/library/threading.html) to share the session class and run it in multiple threads.

**Comment by kokarare1212** [comment]
Since there has been no response for a long time, this issue will be closed.

**Comment by staniel359** [comment]
@kokarare1212 Sorry for no response.
I meant that I have a script and I execute it multiple times. And each time session is created.
I wonder is it possible to initialize Session once and reuse it in each script execution?

**Comment by kokarare1212** [comment]
Basically, you can't reuse the session variables since they are being processed while connected to Spotify's server,
but you may be able to create another scripts (daemon?) to pass the session variables from there.

**Comment by staniel359** [comment]
@kokarare1212 Is it possible do serialize/deserialize `Session` object?

**Comment by kokarare1212** [comment]
I haven't tested it, but I think you need to reconnect if you use pickle or something.

**Comment by staniel359** [comment]
@kokarare1212 I see, thanks.

**Comment by pdtan** [comment]
@kokarare1212 Does session get expired? Any function to check if session is active?

**Comment by kokarare1212** [comment]
As far as I can remember, it probably has an expiration date but has never reached it, and an exception should be thrown if it expires.
