### ISSUE TITLE
"byte == -1" no longer works for detecting end of songs

### ISSUE THREAD

**Issue by ghost** [kokarare1212/librespot-python#81]
With the current version of librespot-python it no longer returns "-1" when the song ends, the best I could figure out was waiting until the byte returned is empty/null but it is by no means perfect so I was wondering if you could look into this issue please.

**Comment by Footsiefat** [comment]
Thanks for the quick reply, with the new method how can I detect the end of the song then?

**Comment by kokarare1212** [comment]
If you write the following, the variable "data" will be filled with music data
```
data = stream.input_stream.stream().read()
```

**Comment by kokarare1212** [comment]
The above code will pass the data up to the end of the song.
The data will be thread-blocked while it is being retrieved internally, so when the function finishes executing, the data will have been stored until the end.

**Comment by kokarare1212** [comment]
The following older branches are not actively maintained, but can be used if needed.
https://github.com/kokarare1212/librespot-python/tree/main

**Comment by Footsiefat** [comment]
Many thanks!
