### ISSUE TITLE
Using 0 because preferred AudioQuality.HIGH couldn't be found.

### ISSUE THREAD

**Issue by Footsiefat** [kokarare1212/librespot-python#86]
I get the following error when trying to stream [https://open.spotify.com/track/4bPQs0PHn4xbipzdPfn6du](https://open.spotify.com/track/4bPQs0PHn4xbipzdPfn6du)

```
Using 0 because preferred AudioQuality.HIGH couldn't be found.
Audio key error, code: 1
Audio key error, code: 1
```

**Comment by kokarare1212** [comment]
Thank you for your inquiry.
I checked here and found out that the Vorbis codec is not supported for that track.
The codec is currently unsupported and will be updated when the porting code is updated.
However, please keep in mind that it is unlikely that the Vorbis codec will be supported.
