### ISSUE TITLE
[BUG] Programs freezes on 2nd login after a failed attempt

### ISSUE THREAD

**Issue by PacketSurf** [kokarare1212/librespot-python#95]
The program freezes if you try to login after a failed login attempt. It doesn't throw any exception, just completely freezes up. I think it ties into another issue I have, where the program freezes while attempting to reconnect to a session after there is a disconnect.

```
from librespot.core import Session

username = ..
password = ..
try:
    SESSION = Session.Builder().user_pass("wrong", "creds").create();
except Exception as e:
    print(e)
try:
    SESSION = Session.Builder().user_pass(username, password).create();
except Exception as e:
    #Never throws exception
    print(e)
#Never reaches here
print('login complete.')
```

**To Reproduce**
change file to .py 
[login_test.txt](https://github.com/kokarare1212/librespot-python/files/7575386/login_test.txt)

**Comment by kokarare1212** [comment]
Thank you for your inquiry.
It seems to be stuck when sending data at login and then receiving data afterwards.
Please wait long enough to figure out the details.

**Comment by PacketSurf** [comment]
So it seems to specifically get stuck while trying to receive data from the socket. This is the traceback when I keyboard interrupt:
```
  SESSION = Session.Builder().user_pass(USERNAME, PW).create();
  File "/opt/anaconda3/lib/python3.8/site-packages/librespot/core.py", line 1224, in create
    session.authenticate(self.login_credentials)
  File "/opt/anaconda3/lib/python3.8/site-packages/librespot/core.py", line 650, in authenticate
    self.__authenticate_partial(credential, False)
  File "/opt/anaconda3/lib/python3.8/site-packages/librespot/core.py", line 972, in __authenticate_partial
    packet = self.cipher_pair.receive_encoded(self.connection)
  File "/opt/anaconda3/lib/python3.8/site-packages/librespot/crypto.py", line 58, in receive_encoded
    header_bytes = self.__receive_cipher.decrypt(connection.read(3))
  File "/opt/anaconda3/lib/python3.8/site-packages/librespot/core.py", line 1481, in read
    return self.__socket.recv(length)
```

**Comment by kokarare1212** [comment]
This has been fixed in the following commit.
The problem was with the initialization of io.BytesIO in the class.
This may be a bug in Python.
Please check it again.
https://github.com/kokarare1212/librespot-python/commit/bd71ecde46d6c77f0653cb23d1174b0a6ac7540f

**Comment by PacketSurf** [comment]
Yep, this appears to have fixed any issues I was having. Thank you for the quick response.
