### ISSUE TITLE
[BUG] AudioFile AttributeError

### ISSUE THREAD

**Issue by Puyodead1** [kokarare1212/librespot-python#97]
latest commit seems to have an issue with https://github.com/kokarare1212/librespot-python/blob/rewrite/librespot/audio/decoders.py#L21 where it should be AAC_24_NORM.

```
    if hasattr(file, "format") and AudioQuality.get_quality(
  File "AppData\Local\Programs\Python\Python310\lib\site-packages\librespot\audio\decoders.py", line 21, in get_quality
    audio_format == AudioFile.AAC_24_NORMAL,
AttributeError: type object 'AudioFile' has no attribute 'AAC_24_NORMAL'
```

**Comment by kokarare1212** [comment]
Thank you for your inquiry.
This has been fixed in the following commit.
e843ac6e64e70de0d8ae008072b7ebb981793f9d
